export const cards = [
  {
    title: "تعداد کل سفارش‌ها",
    content: "96 سفارش",
    status: "down",
    comparisonTime: "ماه قبل",
    comparisonPercentage: "6",
    img: "assets/orders/card-icon.png",
  },
  {
    title: "مجموع فروش این ماه",
    content: "102,000,000 تومان",
    status: "up",
    comparisonTime: "ماه قبل",
    comparisonPercentage: "6",
    img: "assets/orders/card-icon.png",
  },
  {
    title: "میانگین مبلغ هر سفارش",
    content: "1,200,000 تومان",
    status: "up",
    comparisonTime: "ماه قبل",
    comparisonPercentage: "6",
    img: "assets/orders/card-icon.png",
  },
];

export const tabs = [
  "همه",
  "در حال بررسی",
  "در حال آماده سازی",
  "تحویل به پیک",
  "ارسال شده",
  "لغو شده",
  "مرجوع  شده",
];

export const tableData = {
  headers: [
    "شماره سفارش",
    "مبلغ سفارش",
    "تاریخ ثبت سفارش",
    "وضعیت",
    "تعداد کالا",
    "موقعیت خریدار",
    "جزئیات",
  ],
  data: [
    {
      id: "5589693661",
      price: "1,200,000 تومان",
      date: "1404/01/20",
      status: "در حال بررسی",
      quantity: "2",
      location: "تهران",
      details: "more",
    },
    {
      id: "5589693662",
      price: "1,500,000 تومان",
      date: "1404/01/21",
      status: "در حال آماده سازی",
      quantity: "4",
      location: "شیراز",
      details: "more",
    },
    {
      id: "5589693663",
      price: "980,000 تومان",
      date: "1404/01/22",
      status: "تحویل به پیک",
      quantity: "1",
      location: "مشهد",
      details: "more",
    },
    {
      id: "5589693664",
      price: "2,300,000 تومان",
      date: "1404/01/23",
      status: "ارسال شده",
      quantity: "5",
      location: "اصفهان",
      details: "more",
    },
    {
      id: "5589693665",
      price: "870,000 تومان",
      date: "1404/01/24",
      status: "مرجوع شده",
      quantity: "2",
      location: "تبریز",
      details: "more",
    },
    {
      id: "5589693666",
      price: "1,100,000 تومان",
      date: "1404/01/25",
      status: "لغو شده",
      quantity: "3",
      location: "کرج",
      details: "more",
    },
  ],
};
